---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-apps
  namespace: argocd
  labels:
    app: argocd-local-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
